sudo: true
language: python

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.6
      env: TOXENV=py36
install:
  - sudo mkdir -p /travis-install
  - sudo chown travis /travis-install
  # (The conda installation steps below are taken from http://conda.pydata.org/docs/travis.html)
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O /travis-install/miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /travis-install/miniconda.sh;
    fi

  - bash /travis-install/miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - pip install -r dev-requirements.txt
  # Useful for debugging any issues with conda
  - conda info -a
  - pip install mlflow
  script:
  - pytest
  - ./lint.sh