name: main
channels:
  - defaults
dependencies:
  - numpy
  - pandas=0.22.0
  - scikit-learn==0.19.1
  - pip:
    - mlflow
    - pyarrow==0.9.0.post1
    - pyspark==2.3.0
    - xgboost==0.71
    - tensorflow==1.8.0
